### ISSUE TITLE
Discord RPC Song Name Integration Is Broken

### ISSUE THREAD

**Issue by vapronva** [Geoxor/amethyst#16]
## The hell?

Most of the times files display the full file path instead of file name or "artist + name" in Discord Rich Presence Integrations.

### File №1

The displayed song name in RPC contains the full path to the file.

| ![](https://user-images.githubusercontent.com/35921969/170969769-a835179a-71d2-4a5c-84e5-1d93943da18e.png) | ![](https://user-images.githubusercontent.com/35921969/170970095-15a51a7c-135e-4a19-ac9f-e85c7a5d3a0a.png) |
|:--:|:--:|
| *The Discord Rich Presence integration on the opened file* | *The opened file in Amethyst; all metadata is present and displayed correct* |

### File №2

The artist name displayed in RPC is `Various Artists` instead of `Geoxor`.

| ![](https://user-images.githubusercontent.com/35921969/170971022-8b1ba55b-fcdb-4b86-a643-c65c3bba1e2a.png) | ![](https://user-images.githubusercontent.com/35921969/170971146-b6ca0346-f385-4fbd-92b7-d6ea68894946.png) |
|:--:|:--:|
| *The Discord Rich Presence integration on the opened file* | *The opened file in Amethyst; all metadata is present and displayed correct* |

### File №3

The displayed song name in RPC contains the full path to the file.

| ![](https://user-images.githubusercontent.com/35921969/170972619-f9ed29b0-bd06-4507-a3d4-8eb8eb9375b2.png) | ![](https://user-images.githubusercontent.com/35921969/170972715-6aa86fc0-f265-490b-a55a-f0a16f6e3e79.png) |
|:--:|:--:|
| *The Discord Rich Presence integration on the opened file* | *The opened file in Amethyst; all metadata is present and displayed correct* |

### File №4

Everything is fine.

| ![](https://user-images.githubusercontent.com/35921969/170976267-4fc13ed6-8e2b-414d-b639-6196636d830f.png) | ![](https://user-images.githubusercontent.com/35921969/170976323-eb8cf919-7c74-4701-a259-23be4c3bf4cc.png) |
|:--:|:--:|
| *The Discord Rich Presence integration on the opened file* | *The opened file in Amethyst; all metadata is present and displayed correct* |

## Other Information

- **App Version**: `v1.2.9` as of commit [`ada27a`](https://github.com/amethyst-px/amethyst/commit/ada27a826140a093a196553116e716d969b630fd)
- **Desktop Environment**: macOS 12.4

**Comment by Geoxor** [comment]
seems to work correctly, reopen the issue if not fixed
![image](https://user-images.githubusercontent.com/34042825/183761429-d1b10372-6168-4444-99ab-f8bd142a7c6a.png)
