### ISSUE TITLE
progress bar is still going on when I stop that on render

### ISSUE THREAD

**Issue by TheRazan** [Geoxor/amethyst#182]
https://www.dropbox.com/s/gcdtpjzf82l3won/Amethyst%202022-11-22%2019-45-07.mp4?dl=0
https://www.dropbox.com/s/vm39wauunactkxn/Amethyst%202022-11-23%2015-00-17.mp4?dl=0
these are big files so I had to share it with dropbox
so - the problem is this: before the progress bar is finally rendered, i stopped the music.
and then when the bar is rendered, it progresses (without the music playing)

**Comment by Geoxor** [comment]
fixed on https://github.com/Geoxor/amethyst/commit/8ddf1800ccef6594cd9257488abcb1179ea29e8d

**Comment by TheRazan** [comment]
thanks!
