### ISSUE TITLE
progress bar issues

### ISSUE THREAD

**Issue by TheRazan** [Geoxor/Amethyst#190]
as the header suggests, the progress bar can't react to the 5 seconds skip when clicking the left or right arrow on the keyboard

**Comment by otiskujawa** [comment]
Same issue with node sliders while resetting them
[video](https://cdn.discordapp.com/attachments/967797529708212244/1048261649397723278/2022-12-02_16-34-00.mp4)

**Comment by TheRazan** [comment]
In addition, if I do not have amethyst on my screen and it is running in minimized mode, the progress bar goes slower.
![image](https://user-images.githubusercontent.com/116429139/208290270-399b8f9c-7b04-4c53-8bea-ac44e1f66a2e.png)
it is very clear that this is not 3:51/4:17 on the progress bar because the track is noticeably quieter in that part.

**Comment by TheRazan** [comment]
okay I noticed that part of these issues are solved but this will still be open

**Comment by irdkwmnsb** [comment]
> 1st issue of this issue
Which one?
The arrow keys for me work fine.

**Comment by TheRazan** [comment]
> > 1st issue of this issue
> 
> Which one? The arrow keys for me work fine.

1st issue of the issue meaning the arrow keys one is fixed
the 2nd issue which I mentioned 3 weeks ago didn't get fixed, it is still there - I'm talking about the progress bar going slower when Amethyst is in minimized mode.
