### ISSUE TITLE
no such file or directory

### ISSUE THREAD

**Issue by otiskujawa** [Geoxor/amethyst#199]
**Describe the bug**
![image](https://user-images.githubusercontent.com/49094075/205320542-4d25b453-5d4e-4688-bf6c-c32d99479237.png)

**Amethyst Details (required):**
https://github.com/Geoxor/amethyst/commit/4b15317fb40483fb50028a41a2acce1ec94a8d14

**To Reproduce (optional)**
Build to linux using yarn without existing '~/.config/amethyst/Metadata Cache'

**Expected behavior (optional)**
It should do what commands below do
```bash
mkdir --parents ~/.config/amethyst
touch `~/.config/amethyst/Metadata Cache`
```
create directory and file

**Additional context (optional)**
compiled using line in readme

may be related to (comment)

**Comment by otiskujawa** [comment]
#200

**Comment by otiskujawa** [comment]
Errors during packaging (error occurred while using run dev)
```
• building        target=rpm arch=arm64 file=release/build/amethyst-1.8.22.aarch64.rpm
  ⨯ to build rpm, executable rpmbuild is required, please install: sudo apt-get install rpm  
  ⨯ to build rpm, executable rpmbuild is required, please install: sudo apt-get install rpm  
  ⨯ Cannot cleanup: 

Error #1 --------------------------------------------------------------------------------
Error: /home/otiskujawa/Documents/amenew/amethyst2/node_modules/app-builder-bin/linux/x64/app-builder process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
1
    at ChildProcess.<anonymous> (/home/otiskujawa/Documents/amenew/amethyst2/node_modules/builder-util/src/util.ts:250:14)
    at Object.onceWrapper (node:events:514:26)
    at ChildProcess.emit (node:events:394:28)
    at maybeClose (node:internal/child_process:1067:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)

Error #2 --------------------------------------------------------------------------------
Error: /home/otiskujawa/Documents/amenew/amethyst2/node_modules/app-builder-bin/linux/x64/app-builder process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
1
    at ChildProcess.<anonymous> (/home/otiskujawa/Documents/amenew/amethyst2/node_modules/builder-util/src/util.ts:250:14)
    at Object.onceWrapper (node:events:514:26)
    at ChildProcess.emit (node:events:394:28)
    at maybeClose (node:internal/child_process:1067:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)  failedTask=build stackTrace=Error: Cannot cleanup: 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Error #1 --------------------------------------------------------------------------------
Error: /home/otiskujawa/Documents/amenew/amethyst2/node_modules/app-builder-bin/linux/x64/app-builder process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
1
    at ChildProcess.<anonymous> (/home/otiskujawa/Documents/amenew/amethyst2/node_modules/builder-util/src/util.ts:250:14)
    at Object.onceWrapper (node:events:514:26)
    at ChildProcess.emit (node:events:394:28)
    at maybeClose (node:internal/child_process:1067:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Error #2 --------------------------------------------------------------------------------
Error: /home/otiskujawa/Documents/amenew/amethyst2/node_modules/app-builder-bin/linux/x64/app-builder process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
1
    at ChildProcess.<anonymous> (/home/otiskujawa/Documents/amenew/amethyst2/node_modules/builder-util/src/util.ts:250:14)
    at Object.onceWrapper (node:events:514:26)
    at ChildProcess.emit (node:events:394:28)
    at maybeClose (node:internal/child_process:1067:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
    at throwError (/home/otiskujawa/Documents/amenew/amethyst2/node_modules/builder-util/src/asyncTaskManager.ts:88:11)
    at checkErrors (/home/otiskujawa/Documents/amenew/amethyst2/node_modules/builder-util/src/asyncTaskManager.ts:53:9)
    at AsyncTaskManager.awaitTasks (/home/otiskujawa/Documents/amenew/amethyst2/node_modules/builder-util/src/asyncTaskManager.ts:67:7)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Packager.doBuild (/home/otiskujawa/Documents/amenew/amethyst2/node_modules/app-builder-lib/src/packager.ts:453:5)
    at Object.executeFinally (/home/otiskujawa/Documents/amenew/amethyst2/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (/home/otiskujawa/Documents/amenew/amethyst2/node_modules/app-builder-lib/src/packager.ts:376:31)
    at Packager.build (/home/otiskujawa/Documents/amenew/amethyst2/node_modules/app-builder-lib/src/packager.ts:337:12)
    at Object.executeFinally (/home/otiskujawa/Documents/amenew/amethyst2/node_modules/builder-util/src/promise.ts:12:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by otiskujawa** [comment]
building only linux x64 dir went well and fixed issue
![image](https://user-images.githubusercontent.com/49094075/205325352-2b2c97fe-c7c4-43dc-831d-c1c96449a698.png)
![image](https://user-images.githubusercontent.com/49094075/205325520-070e9b7f-e496-4076-80f9-d5626c60bbe0.png)
so yarn run dev doesn't work

**Comment by Geoxor** [comment]
> Errors during packaging (error occurred while using run dev)
> 
> ```
> • building        target=rpm arch=arm64 file=release/build/amethyst-1.8.22.aarch64.rpm
>   ⨯ to build rpm, executable rpmbuild is required, please install: sudo apt-get install rpm  
>   ⨯ to build rpm, executable rpmbuild is required, please install: sudo apt-get install rpm  
>   ⨯ Cannot cleanup: 
> 
> Error #1 --------------------------------------------------------------------------------
> Error: /home/otiskujawa/Documents/amenew/amethyst2/node_modules/app-builder-bin/linux/x64/app-builder process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
> Exit code:
> 1
>     at ChildProcess.<anonymous> (/home/otiskujawa/Documents/amenew/amethyst2/node_modules/builder-util/src/util.ts:250:14)
>     at Object.onceWrapper (node:events:514:26)
>     at ChildProcess.emit (node:events:394:28)
>     at maybeClose (node:internal/child_process:1067:16)
>     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
> 
> Error #2 --------------------------------------------------------------------------------
> Error: /home/otiskujawa/Documents/amenew/amethyst2/node_modules/app-builder-bin/linux/x64/app-builder process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
> Exit code:
> 1
>     at ChildProcess.<anonymous> (/home/otiskujawa/Documents/amenew/amethyst2/node_modules/builder-util/src/util.ts:250:14)
>     at Object.onceWrapper (node:events:514:26)
>     at ChildProcess.emit (node:events:394:28)
>     at maybeClose (node:internal/child_process:1067:16)
>     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)  failedTask=build stackTrace=Error: Cannot cleanup: 
>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Error #1 --------------------------------------------------------------------------------
> Error: /home/otiskujawa/Documents/amenew/amethyst2/node_modules/app-builder-bin/linux/x64/app-builder process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
> Exit code:
> 1
>     at ChildProcess.<anonymous> (/home/otiskujawa/Documents/amenew/amethyst2/node_modules/builder-util/src/util.ts:250:14)
>     at Object.onceWrapper (node:events:514:26)
>     at ChildProcess.emit (node:events:394:28)
>     at maybeClose (node:internal/child_process:1067:16)
>     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Error #2 --------------------------------------------------------------------------------
> Error: /home/otiskujawa/Documents/amenew/amethyst2/node_modules/app-builder-bin/linux/x64/app-builder process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
> Exit code:
> 1
>     at ChildProcess.<anonymous> (/home/otiskujawa/Documents/amenew/amethyst2/node_modules/builder-util/src/util.ts:250:14)
>     at Object.onceWrapper (node:events:514:26)
>     at ChildProcess.emit (node:events:394:28)
>     at maybeClose (node:internal/child_process:1067:16)
>     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
>     at throwError (/home/otiskujawa/Documents/amenew/amethyst2/node_modules/builder-util/src/asyncTaskManager.ts:88:11)
>     at checkErrors (/home/otiskujawa/Documents/amenew/amethyst2/node_modules/builder-util/src/asyncTaskManager.ts:53:9)
>     at AsyncTaskManager.awaitTasks (/home/otiskujawa/Documents/amenew/amethyst2/node_modules/builder-util/src/asyncTaskManager.ts:67:7)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at Packager.doBuild (/home/otiskujawa/Documents/amenew/amethyst2/node_modules/app-builder-lib/src/packager.ts:453:5)
>     at Object.executeFinally (/home/otiskujawa/Documents/amenew/amethyst2/node_modules/builder-util/src/promise.ts:12:14)
>     at Packager._build (/home/otiskujawa/Documents/amenew/amethyst2/node_modules/app-builder-lib/src/packager.ts:376:31)
>     at Packager.build (/home/otiskujawa/Documents/amenew/amethyst2/node_modules/app-builder-lib/src/packager.ts:337:12)
>     at Object.executeFinally (/home/otiskujawa/Documents/amenew/amethyst2/node_modules/builder-util/src/promise.ts:12:14)
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> ```

This is due to the npm script building for different package managers from the linux config in package.json. you're on arch so you probably don't need to build for rpm

**Comment by otiskujawa** [comment]
This file is not created while installing
![image](https://user-images.githubusercontent.com/49094075/205489585-f4e9a9d9-ddd3-44c6-ae4f-d66d99c72e04.png)
