### ISSUE TITLE
node out of screen after adding

### ISSUE THREAD

**Issue by otiskujawa** [Geoxor/Amethyst#252]
new node is out of screen on default size of app
![image](https://user-images.githubusercontent.com/49094075/208175050-84f18818-440f-4dd3-ac3a-96febf5958d0.png)
![image](https://user-images.githubusercontent.com/49094075/208175069-fe398009-372a-4ccf-b0db-202b0c08f1b5.png)

**Comment by Geoxor** [comment]
fixed from aa0762f56226afef7397369609894d9df8c03882
