### ISSUE TITLE
Amethyst launches but wont display on Arch

### ISSUE THREAD

**Issue by freqawi** [Geoxor/Amethyst#259]
**Describe the bug**
Launching amethyst is fine but nothing happens, system monitor shows amethyst as an open application using memory but no window opened.

**Amethyst Details (required):**
 - Version v1.8.34
**To Reproduce (optional)**
1. Don't know what is causing it, can't even find any logs (not that I would know how to anyways..)

**Expected behavior (optional)**
window opens yep you already knew this

**Screenshots (optional)**
nothing to show it doesn't even start up

**Additional context (optional)**
using garuda distribution of arch linux

**Comment by Geoxor** [comment]
I assume you're running a production version?, if so could you execute the amethyst binary through a terminal?, `v.1.8.34` is not on AUR yet so it could be an issue with the installation

In dev mode it works on my VM
![image](https://user-images.githubusercontent.com/34042825/208720422-080564b7-50ad-4cdc-8c51-e42521890803.png)

**Comment by Kycb42148** [comment]
I have installed Amethyst (v1.8.22) from AUR and got the same problem
Then I launched it from terminal and saw this error:
`Error: ENOENT: no such file or directory, stat '/home/kycb/.config/amethyst/Metadata Cache'`
After I created `~/.config/amethyst/Metadata Cache` directory, Amethyst started normally
Perhaps, this can help
![Screenshot from 2022-12-20 22-11-01](https://user-images.githubusercontent.com/34296702/208759223-67cb555b-6b6f-4959-b274-de6b87608052.png)

**Comment by tsgfrequency** [comment]
Uncaught Exception:
Error: ENOENT: no such file or directory, stat '/home/user/.config/amethyst/Metadata Cache'
at statSync (node:fs:1551:3)
at e.statSync (node:electron/js2c/asar_bundle:5:4539)
at Object.<anonymous> (/opt/amethyst/resources/app.asar/release/dist/main/mainWindow.js:42:14)
at Module._compile (node:internal/modules/cjs/loader:1120:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1175:10)
at Module.load (node:internal/modules/cjs/loader:988:32)
at Module._load (node:internal/modules/cjs/loader:829:12)
at c._load (node:electron/js2c/asar_bundle:5:13343)
at Module.require (node:internal/modules/cjs/loader:1012:19)
at require (node:internal/modules/cjs/helpers:102:18)

**Comment by tsgfrequency** [comment]
Building from souce does this:

yarn build:renderer exited with code 0
• electron-builder  version=23.6.0 os=6.0.12-zen1-1-zen
• loaded configuration  file=package.json ("build" field)
• writing effective config  file=release/build/builder-effective-config.yaml
• rebuilding native dependencies  dependencies=register-scheme@0.0.2, sharp@0.31.2 platform=linux arch=x64
• install prebuilt binary  name=sharp version=0.31.2 platform=linux arch=x64 napi=
• rebuilding native dependency  name=register-scheme version=0.0.2
• packaging       platform=linux arch=x64 electron=20.3.7 appOutDir=release/build/linux-unpacked
• building        target=AppImage arch=x64 file=release/build/Amethyst-1.8.35.AppImage
• building        target=snap arch=x64 file=release/build/amethyst_1.8.35_amd64.snap
• rebuilding native dependencies  dependencies=register-scheme@0.0.2, sharp@0.31.2 platform=linux arch=arm64
• install prebuilt binary  name=sharp version=0.31.2 platform=linux arch=arm64 napi=
• rebuilding native dependency  name=register-scheme version=0.0.2
• packaging       platform=linux arch=arm64 electron=20.3.7 appOutDir=release/build/linux-arm64-unpacked
• building        target=deb arch=x64 file=release/build/amethyst_1.8.35_amd64.deb
• building        target=AppImage arch=arm64 file=release/build/Amethyst-1.8.35-arm64.AppImage
• building        target=deb arch=arm64 file=release/build/amethyst_1.8.35_arm64.deb
• building        target=rpm arch=x64 file=release/build/amethyst-1.8.35.x86_64.rpm

(Important stuff)
⨯ to build rpm, executable rpmbuild is required, please install: sudo apt-get install rpm
• building        target=rpm arch=arm64 file=release/build/amethyst-1.8.35.aarch64.rpm
⨯ to build rpm, executable rpmbuild is required, please install: sudo apt-get install rpm
⨯ Cannot cleanup:

**Comment by Geoxor** [comment]
`Error: ENOENT: no such file or directory, stat '/home/user/.config/amethyst/Metadata Cache'`

I've seen this error before but i thought i fixed it already https://github.com/Geoxor/Amethyst/commit/d1af8f39882bb2cdfba70d323de3aa81a88c7838,

**Comment by Geoxor** [comment]
> Building from souce does this:
> 
> yarn build:renderer exited with code 0 • electron-builder version=23.6.0 os=6.0.12-zen1-1-zen • loaded configuration file=package.json ("build" field) • writing effective config file=release/build/builder-effective-config.yaml • rebuilding native dependencies dependencies=register-scheme@0.0.2, sharp@0.31.2 platform=linux arch=x64 • install prebuilt binary name=sharp version=0.31.2 platform=linux arch=x64 napi= • rebuilding native dependency name=register-scheme version=0.0.2 • packaging platform=linux arch=x64 electron=20.3.7 appOutDir=release/build/linux-unpacked • building target=AppImage arch=x64 file=release/build/Amethyst-1.8.35.AppImage • building target=snap arch=x64 file=release/build/amethyst_1.8.35_amd64.snap • rebuilding native dependencies dependencies=register-scheme@0.0.2, sharp@0.31.2 platform=linux arch=arm64 • install prebuilt binary name=sharp version=0.31.2 platform=linux arch=arm64 napi= • rebuilding native dependency name=register-scheme version=0.0.2 • packaging platform=linux arch=arm64 electron=20.3.7 appOutDir=release/build/linux-arm64-unpacked • building target=deb arch=x64 file=release/build/amethyst_1.8.35_amd64.deb • building target=AppImage arch=arm64 file=release/build/Amethyst-1.8.35-arm64.AppImage • building target=deb arch=arm64 file=release/build/amethyst_1.8.35_arm64.deb
> 
> (Important stuff) • building target=rpm arch=x64 file=release/build/amethyst-1.8.35.x86_64.rpm ⨯ to build rpm, executable rpmbuild is required, please install: sudo apt-get install rpm • building target=rpm arch=arm64 file=release/build/amethyst-1.8.35.aarch64.rpm ⨯ to build rpm, executable rpmbuild is required, please install: sudo apt-get install rpm ⨯ Cannot cleanup:

This failed because by default electron-builder will compile for `AppImage` `deb` `rpm` and `snap`, you're missing dependencies to compile for all of those, so instead try doing `yarn package --linux dir` and it should build it inside `release/build/linux-unpacked`, sorry if this is kinda inconvenient, i am not that good at arch and i think the `yarn package` script can be improved 🤯

**Comment by freqawi** [comment]
Sorry for disappearing but it worked! thank you so much for your help!

**Comment by Geoxor** [comment]
no problem 🤯🐇
