### ISSUE TITLE
`waveformRenderWorker.ts` does not exist on production version

### ISSUE THREAD

**Issue by Geoxor** [Geoxor/amethyst#32]

**Comment by Yukiiro-Nite** [comment]
@Geoxor I believe we need to change https://github.com/Geoxor/amethyst/blob/master/src/renderer/waveformRenderer.ts#L113
to this:
```
this.currentWorker = new Worker(new URL("./workers/waveformRenderWorker.ts", import.meta.url));
```

According to [this github issue](https://github.com/vitejs/vite/issues/4642) vite won't include a web worker in the build unless one does this. I'm sorry I didn't notice when I added the original waveformRenderer.

I'll make a PR for this tomorrow.
