### ISSUE TITLE
Infinite queue scroll

### ISSUE THREAD

**Issue by sfaresee** [Geoxor/amethyst#34]
Infinite scroll in the queue section. 

Queue resorting makes the screen white

**Comment by sfaresee** [comment]
Also title in the queue is overlapping
![image](https://user-images.githubusercontent.com/57977673/182195750-a3ef6e0e-0998-4194-81a7-ff85ccdde2d1.png)

**Comment by Geoxor** [comment]
> Also title in the queue is overlapping ![image](https://user-images.githubusercontent.com/57977673/182195750-a3ef6e0e-0998-4194-81a7-ff85ccdde2d1.png)

Fixed this now https://github.com/amethyst-px/amethyst/commit/7c9cf775ba12df57168435c0bc11536e68836de1

Next time make multiple issues for each problem
