### ISSUE TITLE
When "starting a song again", slider won't reset

### ISSUE THREAD

**Issue by CallMeYuuuu** [Geoxor/Amethyst#375]
**Describe the bug**
When clicking on a song which is already playing in the song list, the song starts over but the visual slider (idk what to call this thing) won't reset
![image](https://user-images.githubusercontent.com/44119696/214264895-0a464fc9-f471-4e80-9873-e72acf116220.png)

**Amethyst Details (required):**
 - Version 1.8.43

**To Reproduce (optional)**
1. Play any song
2. Click on the same song which is currently playing in the song list

**Comment by TheRazan** [comment]
also happens when repeat mode is on

**Comment by Geoxor** [comment]
i am losing my mind with this stupid waveform.js library, the code is so bloated

**Comment by Geoxor** [comment]
closing cus waveform.js no longer exists in amethyst
