### ISSUE TITLE
Normal linux user testing: Debian 11

### ISSUE THREAD

**Issue by otiskujawa** [Geoxor/Amethyst#423]
**Describe the bug**
I decided to try to install amethyst just like normal user will do on some systems
Debian 11 is first of them because i already had vm with it
Here are results (those can help users in future, make more documentation about building etc.)
Building from source using [docs](https://amethyst.pages.dev/installation/build_from_source.html)
![image](https://user-images.githubusercontent.com/49094075/217306352-86e969d9-bcaa-4cfc-b54e-aa4b01e67587.png)
## Installing dependencies
`apt install git npm`
`npm install --global node yarn` (yarn and node are outdated in Debian 11 repo so best way is to use npm)

## Result
`yarn run dev`
![image](https://user-images.githubusercontent.com/49094075/217308528-2a5ebd84-c609-47c0-96e3-422a6e4ae5ba.png)
App starts but playing song returns 404 ( issue #200 reopen )

`yarn run build`
`electron-builder build -l dir`
`./release/build/linux-unpacked/amethyst`

![image](https://user-images.githubusercontent.com/49094075/217309805-6a57f563-7940-49ca-98f3-a64d0e058ba1.png)
Everything seems to be ok

![image](https://user-images.githubusercontent.com/49094075/217310411-c31961ea-9e76-47fa-b1c6-e84c600d9257.png)

This bug report can be used as request for documentation (build tutorial) or closed and mentioned if someone will have same problem.

**Comment by Geoxor** [comment]
closing this because docs suggest to install missing deps already https://amethyst.pages.dev/developing/setting_up_environment.html#prerequisites
