### ISSUE TITLE
Amethyst doesn't show up but is running in the Background 

### ISSUE THREAD

**Issue by Sirius3331** [Geoxor/Amethyst#431]
Amethyst is running on my Arch based distro (Endeavour OS) with the GNOME gui and a LTS Kernel (5.15.93-1-lts). If I think correct was Amethyst working at the first start but later after I wanted to run it again it doesn't show up but in the task manager it was running. Is it possible that wayland is the Problem because only gnome is using it at the time if I am right. I had the LTS Kernel before Amethyst because my Notebook got hibernate problems with the Normal Kernel.

**Comment by Sirius3331** [comment]
I tested it with Cinnamon now but it doesn't work either

**Comment by freqawi** [comment]
Don't use the AUR, the build on there is old and the issue you faced was fixed in the recent versions.

**Comment by Sirius3331** [comment]
Yeah I saw that already. I close the content because it's already solved in the newer versions.
