### ISSUE TITLE
Maybe do something with cover when there is no song loaded

### ISSUE THREAD

**Issue by otiskujawa** [Geoxor/Amethyst#436]
borders of not loaded covers are visible as white and without border radius
It looks bad and is first thing you see after starting app
![image](https://user-images.githubusercontent.com/49094075/219133923-b40417a9-7155-4f70-a6e0-c5383cb90237.png)

It probably can be changed to look like this
![image](https://user-images.githubusercontent.com/49094075/219134982-2fe6a989-5e01-41f4-9937-6629efd65526.png)

**Comment by TheRazan** [comment]
can also be done in songs without cover
