### ISSUE TITLE
Hide dB meters when there is no need for them

### ISSUE THREAD

**Issue by otiskujawa** [Geoxor/Amethyst#437]
**Describe the idea you'd like for Amethyst to have**
I have stereo audio and stereo headphones on laptop
Why do i see 8 dB meters?

![image](https://user-images.githubusercontent.com/49094075/219135927-e504e762-ddd7-493c-afe9-6e54117579d5.png)

Shouldn't it be changed to max channels of system or audio (or just bigger of them)?

![image](https://user-images.githubusercontent.com/49094075/219136319-c2cf6d56-cbe4-4753-92c0-2bcaaa416f3e.png)

**Comment by TheRazan** [comment]
> **Describe the idea you'd like for Amethyst to have** I have stereo audio and stereo headphones on laptop Why do i see 8 dB meters?
try turning it off and on again then it fixes itself
but at 1st installation of the update 1.18.55 it does happen
