### ISSUE TITLE
Stop media button starts first song

### ISSUE THREAD

**Issue by otiskujawa** [Geoxor/amethyst#49]
When i do `playerctl stop`(click stop button) amethyst starts playing first song (even if it was paused)
If first song is playing or paused, it ignores it

**Comment by otiskujawa** [comment]
ps: i used npm run dev on this [version](https://github.com/Geoxor/amethyst/commit/dc838eec92e58b751c88fa773c39eec1fcddb14c)

**Comment by otiskujawa** [comment]
https://cdn.discordapp.com/attachments/967797529708212244/1033699999315394610/2022-10-23_13-12-17.mp4

**Comment by BusteanHAN** [comment]
bro i fixed it by accident

**Comment by Geoxor** [comment]
seems to be the case, reopen if false
