### ISSUE TITLE
Music speeds up or buggy on beggining

### ISSUE THREAD

**Issue by otiskujawa** [Geoxor/amethyst#53]
Music speeds up or buggy on beginning when i start song that wasn't played before
[Movie1](https://cdn.discordapp.com/attachments/967797529708212244/1030803482501980240/2022-10-15_13-21-13.mp4)
[Movie2](https://cdn.discordapp.com/attachments/967797529708212244/1030805170830987294/2022-10-15_13-29-50.mp4)

**Comment by otiskujawa** [comment]
https://user-images.githubusercontent.com/49094075/195984641-8db9debb-76b4-4d0d-bc9c-725c12ff4125.mp4

**Comment by Geoxor** [comment]
yeah i notice this error started happening once i implemented the audio routing
probably something to do with this
https://github.com/Geoxor/amethyst/blob/7f78fdb9f4cbfbcf0d6530cac2bd8dd2fb8f316a/src/renderer/player.ts#L156-L160
