### ISSUE TITLE
Show album art instead of file type in Discord RPC

### ISSUE THREAD

**Issue by okawaffles** [Geoxor/Amethyst#551]
**Describe the idea you'd like for Amethyst to have**
I would like Amethyst to send album art to Discord's RPC instead of the file type, similar to how Spotify's status is shown.

**Is your feature request related to a problem? Please describe.**
No.

**Additional context**
Where the file-music-note icon is?
![image](https://github.com/Geoxor/Amethyst/assets/77750838/35f24870-d15b-4156-ad05-aec4828036db)

**Comment by LayreBoi** [comment]
I don't think this will work for programs other than Spotify who has partnered with Discord. You can't simply upload an image into the Art Assets in Discord and use it in the RPC. The Art Assets are stored in the server with an image key, which programs have to use to display a picture in the RPC.

**Comment by okawaffles** [comment]
Ah I see. That makes sense.
