### ISSUE TITLE
debug panel bug

### ISSUE THREAD

**Issue by m1chiguni386** [Geoxor/Amethyst#634]
**Describe the bug**
When you click on fps in debug panel two parameters going crazy and showing "-infinity".

**Amethyst Details (required):**
 - Version [v1.9.16]

**To Reproduce (optional)**
1. Enable Debug panel
2. Click on fps

**Expected behavior (optional)**
It will be showing right value not "-infinity"

**Screenshots (optional)**
![Снимок экрана 2023-10-27 145943](https://github.com/Geoxor/Amethyst/assets/148101314/000733e9-f653-4ad9-a381-023e5a515847)

**Comment by Geoxor** [comment]
That is intended design, it's meant for clearing the min/max
