### ISSUE TITLE
UI unreadable sometimes

### ISSUE THREAD

**Issue by InvitedToHell** [Geoxor/amethyst#68]
As shown in the image, with some covers the text on the bottom right is unreadable. Windows has this readability thing in the accent color menu. You cant pick some colors there, because they would cause unreadability. Maybe something like that would help? 

![image](https://user-images.githubusercontent.com/73737531/197015860-b42dcd8e-a816-498f-b6a7-95a33c8f7eb1.png)

**Comment by Geoxor** [comment]
yeah i knew that was going to happen with that feature, i need some help figuring out the math for calculating light colors or something for the buttons etc cus im dumb ☠️💀☠️

**Comment by InvitedToHell** [comment]
> yeah i knew that was going to happen with that feature, i need some help figuring out the math for calculating light colors or something for the buttons etc cus im dumb ☠️💀☠️

Lmao yes dont worry dont worry. I also don't know how you would calculate colors but well. Maybe somebody can help. I tried to look it up but I can't find anything because I have no idea how to google that issue lmao

**Comment by Geoxor** [comment]
this should not be a problem now with the new ambient background system
