### ISSUE TITLE
Vectorscope depends on volume

### ISSUE THREAD

**Issue by otiskujawa** [Geoxor/amethyst#74]
![image](https://user-images.githubusercontent.com/49094075/197402116-353f046b-5532-4c47-a594-3229061e5004.png)
![image](https://user-images.githubusercontent.com/49094075/197402124-ea91f5c4-36fb-4ca3-aa0e-065617e1c524.png)
I am usually listening to music at low volume

**Comment by Geoxor** [comment]
yeah we gotta fix that, this issue reoccured because of the implications regarding https://github.com/Geoxor/amethyst/issues/53

**Comment by BusteanHAN** [comment]
So we made #106 and made it so that the slider affects the master node at the end, however, the vectorscope and spectrum at the  bottom of the screen connect after the slider gain, so this will persist;

We would need to ad pre and post for this to get fixed.

**Comment by Geoxor** [comment]
no longer an issue due to this being intended behaviour from the 'master' node
