### ISSUE TITLE
borders near nodes element

### ISSUE THREAD

**Issue by otiskujawa** [Geoxor/amethyst#76]
remove this border on right or add border on left of nodes
line 98 of [src/renderer/views/Home.vue](https://github.com/Geoxor/amethyst/blob/master/src/renderer/views/Home.vue)

![image](https://user-images.githubusercontent.com/49094075/197404637-0fcb67dc-1d7e-4465-9b7c-e5873c573187.png)
Removed:
![image](https://user-images.githubusercontent.com/49094075/197404653-a5136a6c-5bfe-4083-8386-51dc41c58252.png)
Added on left:
![image](https://user-images.githubusercontent.com/49094075/197404758-4bd71c72-95c2-45d5-903b-81edb2f34bf0.png)

![image](https://user-images.githubusercontent.com/49094075/197405166-0b225da4-a3f3-4902-95eb-99e12bd0befe.png)

**Comment by Geoxor** [comment]
![image](https://user-images.githubusercontent.com/34042825/197410626-fe3b16eb-6372-41d4-8812-34da807fee44.png)
the left side has a border already wdym

**Comment by otiskujawa** [comment]
i propably had older version
