### ISSUE TITLE
Right-click on slider to restore default value

### ISSUE THREAD

**Issue by otiskujawa** [Geoxor/amethyst#96]
Right-click on node slider to restore default value
![image](https://user-images.githubusercontent.com/49094075/198109412-3e43df18-1d6e-4f09-a620-a64853ef3995.png)
or option in this menu for restoring default values
![image](https://user-images.githubusercontent.com/49094075/198109662-407fb9ee-b40d-4fc4-8c9a-da6700c710d3.png)

**Comment by BusteanHAN** [comment]
We added a reset context menu option in #107 ; it functions but the UI does not update yet.

**Comment by Geoxor** [comment]
already implemented
